desiquotes/quotes/urls.py
from django.conf.urls import url

from desiquotes.quotes import views

app_name = 'quotes'

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^user/$', views.user_quotes, name='user_quotes'),
    url(r'^user/name(?P<name>[-\w]+)$', views.user_quotes, name='user_quotes'),
    url(r'^author/name(?P<name>[-\w]+)$', views.user_quotes, name='user_quotes'),
    url(r'^user/write/$', views.CreateUserQuote.as_view(), name='add_user_quote'),
    url(r'^author/write/$', views.CreateAuthorQuote.as_view(), name='add_author_quote'),
    url(r'^user/edit/(?P<pk>\d+)/$', views.EditUserQuote.as_view(), name='edit_user_quote'),
    url(r'^author/edit/(?P<pk>\d+)/$', views.EditAuthorQuote.as_view(), name='edit_author_quote'),
    url(r'^home/$', views.home, name='home'),
    url(r'^preview/$', views.preview, name='preview'),
    url(r'^remove/$', views.remove, name='remove'),
    url(r'^like/$', views.like, name='like'),
    url(r'^drafts/$', views.drafts, name='drafts'),
    url(r'^tag/(?P<tag_name>.+)/$', views.tag, name='tag'),
    url(r'^(?P<slug>[-\w]+)/$', views.quote, name='quote'),
]

desiquotes/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from desiquotes.core import views as core_views
from desiquotes.quotes import views as quotes_views
from desiquotes.authentication import views as quotes_auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
     #url(r'^$', core_views.home, name='home'),
     url(r'^$', quotes_views.home, name='home'),
     url(r'^account/login', auth_views.login, {'template_name': 'core/login.html'}, name='login'),
     url(r'^account/logout', auth_views.logout, {'template_name': 'core/logged_out.html'}, name='logout'),
     url(r'^account/password_reset/$', auth_views.password_reset, {'template_name': 'core/password_reset.html'}, name="password_reset"),
     url(r'^account/password_reset/done/$', auth_views.password_reset_done, {'template_name': 'core/password_reset_done.html'}, name='password_reset_done'),
     url(r'^account/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
             auth_views.password_reset_confirm, {'template_name': 'core/password_reset_confirm.html'}, name='password_reset_confirm'),
     url(r'^account/password_reset/complete/$', auth_views.password_reset_complete, {'template_name': 'core/password_reset_complete.html'}, name='password_reset_complete'),
     url(r'^signup/$', quotes_auth_views.signup, name='signup'),

     url(r'^settings/$', core_views.settings, name='settings'),
     url(r'^settings/picture/$', core_views.picture, name='picture'),
     url(r'^settings/upload_picture/$', core_views.upload_picture, name='upload_picture'),
     url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture, name='save_uploaded_picture'),
     url(r'^settings/password/$', core_views.password, name='password'),

     url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),

     url(r'^quotes/', include('desiquotes.quotes.urls')),
     url(r'^admin/', admin.site.urls)
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

desiquotes/quotes/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType

#from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models
#from autoslug import AutoSlugField
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.db.models import Count
from desiquotes.activities.models import Activity
from django.contrib.contenttypes.fields import GenericRelation


#import markdown
from taggit.managers import TaggableManager

@python_2_unicode_compatible
class Quote(models.Model):
    DRAFT = 'D'
    PUBLISHED = 'P'
    STATUS = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
    )
 
    USER = 'U'
    AUTHOR = 'A'
    WRITER_CHOICES = ( 
        (USER, 'User'),
        (AUTHOR, 'Author'),
    )

    content = models.TextField(max_length=4000)
    tags = TaggableManager()
    #likes = models.IntegerField(default=0)
    likes = GenericRelation(Activity)
    status = models.CharField(max_length=1, choices=STATUS, default=DRAFT)
    writer_type = models.CharField(max_length=1, choices=WRITER_CHOICES, default=USER)
    #create_user = models.ForeignKey(User)
    create_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)
    update_user = models.ForeignKey(User, null=True, blank=True, related_name="+")

    # Below the mandatory fields for generic relation
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, null=True)
    object_id    = models.PositiveIntegerField(null=True)
    content_object     = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = _("Quote")
        verbose_name_plural = _("Quotes")
        ordering = ("-create_date",)

    def __str__(self):
        return self.content
    """
    def get_content_as_markdown(self):
        return markdown.markdown(self.content, safe_mode='escape')
    """	
    @staticmethod
    def get_published(tag_name=None):
        if tag_name is None:
            quotes = Quote.objects.filter(status=Quote.PUBLISHED)
        else:
            quotes = Quote.objects.filter(tags__name=tag_name).filter(status='P')
        return quotes    

    def get_user_published(self,tag_name=None):
        if tag_name is None:
            #quotes = Quote.objects.filter(status=Quote.PUBLISHED,create_user=self.pk)
            quotes = Quote.objects.filter(status=Quote.PUBLISHED,object_id=self.pk)
        else:
            #quotes = Quote.objects.filter(tags__name=tag_name).filter(status=Quote.PUBLISHED,create_user=self.pk)
            quotes = Quote.objects.filter(tags__name=tag_name).filter(status=Quote.PUBLISHED,object_id=self.pk)
        return quotes

    @staticmethod
    def get_counted_tags():
        tag_dict = {}
        query = Quote.objects.filter(status='P').annotate(tagged=Count(
            'tags')).filter(tags__gt=0)
        for obj in query:
            for tag in obj.tags.names():
                if tag not in tag_dict:
                    tag_dict[tag] = 1

                else:  # pragma: no cover
                    tag_dict[tag] += 1

        return tag_dict.items()

    def get_summary(self):
        if len(self.content) > 255:
            return '{0}...'.format(self.content[:255])
        else:
            return self.content

    def calculate_likes(self):
        #likes = QuoteActivity.objects.filter(activity_type=QuoteActivity.LIKE, quote=self.pk).count()
        #self.likes = likes
        #self.save()
        return self.likes.count()
  
    def get_likes(self):
        #likes = QuoteActivity.objects.filter(activity_type=QuoteActivity.LIKE, quote=self.pk)
        #quote=self.pk
        #likes = quote.likes.filter(activity_type=Activity.LIKE)
        return self.likes.count()
        #return likes 

    def get_likers(self):
        likes = self.get_likes()
        likers = []
        for like in likes:
            likers.append(like.user)
        return likers	

    @property
    def get_tags(self):
        return self.tags.slugs()

    def get_writer_type(self):
        return self.writer_type

    """
    def get_tags(self):
        return Tag.objects.filter(quote=self)
    """

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Quote._meta.fields]

    """
    def get_summary_as_markdown(self):
        return markdown.markdown(self.get_summary(), safe_mode='escape')
    """
@python_2_unicode_compatible
class Tag(models.Model):
    tag = models.CharField(max_length=50)
    quote = models.ForeignKey(Quote)

    class Meta:
        verbose_name = _('Tag')
        verbose_name_plural = _('Tags')
        unique_together = (('tag', 'quote'),)
        index_together = [['tag', 'quote'], ]

    def __str__(self):
        return self.tag

    @staticmethod
    def get_popular_tags():
        tags = Tag.objects.all()
        count = {}
        for tag in tags:
            if tag.quote.status == Quote.PUBLISHED:
                if tag.tag in count:
                    count[tag.tag] = count[tag.tag] + 1
                else:
                    count[tag.tag] = 1
        sorted_count = sorted(count.items(), key=lambda t: t[1], reverse=True)
        return sorted_count[:20]

desiquotes/quotes/forms.py
from django import forms

from desiquotes.quotes.models import Quote


class QuoteForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        max_length=4000)

    class Meta:
        model = Quote
        fields = ['content', 'tags', 'status']

desiquotes/quotes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, UpdateView
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.core.urlresolvers import reverse_lazy

from desiquotes.activities.models import Activity
from django.contrib.contenttypes.models import ContentType


#import markdown
from desiquotes.quotes.forms import QuoteForm
from desiquotes.quotes.models import Quote
from desiquotes.decorators import ajax_required
import pprint
import numpy as np


def _quotes(request, quotes):
    paginator = Paginator(quotes, 10)
    page = request.GET.get('page')
    try:
        quotes = paginator.page(page)

    except PageNotAnInteger:
        quotes = paginator.page(1)

    except EmptyPage:   # pragma: no cover
        quotes = paginator.page(paginator.num_pages)

    popular_tags = Quote.get_counted_tags()

    return {
        'quotes': quotes,
        'popular_tags': popular_tags
    }

class CreateUserQuote(LoginRequiredMixin, CreateView):
    template_name = 'quotes/add_user_quote.html'
    form_class = QuoteForm
    success_url = reverse_lazy('quotes:user_quotes')

    def form_valid(self, form):
        #form.instance.create_user = self.request.user
        form.instance.content_object = self.request.user
        form.instance.object_id = self.request.user.id 
        form.instance.writer_type = Quote.USER

        return super(CreateUserQuote, self).form_valid(form)


class EditUserQuote(LoginRequiredMixin, UpdateView):
    template_name = 'quotes/edit_user_quote.html'
    model = Quote
    form_class = QuoteForm
    #success_url = reverse_lazy('quotes:quotes')

class CreateAuthorQuote(LoginRequiredMixin, CreateView):
    model = Quote
    #success_url = reverse_lazy('quotes:quotes')

class EditAuthorQuote(LoginRequiredMixin, UpdateView):
    model = Quote
    #success_url = reverse_lazy('quotes:quotes')

def home(request):
    quotes = Quote.get_published()
    return  render(request, 'quotes/quotes.html', _quotes(request, quotes))

@login_required
def user_quotes(request, name=None):
    logged_in_user = request.user
    quotes = Quote.get_user_published(logged_in_user)
    return  render(request, 'quotes/quotes.html', _quotes(request, quotes))

@login_required
def quote(request, slug):
    quote = get_object_or_404(Quote, slug=slug, status=Quote.PUBLISHED)
    return render(request, 'quotes/quote.html', {'quote': quote})


@login_required
def tag(request, tag_name):
    #quotes = Quote.objects.filter(tags__name=tag_name).filter(status='P')
    quotes = Quote.get_published(tag_name=tag_name)
    return render(request, 'quotes/quotes.html', _quotes(request, quotes))


@login_required
def drafts(request):
    #drafts = Quote.objects.filter(create_user=request.user, status=Quote.DRAFT)
    drafts = Quote.objects.filter(object_id=request.user.id, status=Quote.DRAFT)
    return render(request, 'quotes/drafts.html', {'drafts': drafts})


@login_required
@ajax_required
def preview(request):
    try:
        if request.method == 'POST':
            content = request.POST.get('content')
            html = 'Nothing to display :('
            if len(content.strip()) > 0:
                #html = markdown.markdown(content, safe_mode='escape')
                html = content

            return HttpResponse(html)

        else:
            return HttpResponseBadRequest()

    except Exception:
        return HttpResponseBadRequest()


@login_required
@ajax_required
def remove(request):
    try:
        quote_id = request.POST.get('quote')
        quote = Quote.objects.get(pk=quote_id)
        #if quote.create_user == request.user:
        if quote.object_id == request.user.id:
            """ 
            likes = quote.get_likes()
            for like in likes:
                like.delete()
            """
            quote.delete()
            return HttpResponse()
        else:
            return HttpResponseForbidden()
    except Exception:
        return HttpResponseBadRequest()

@login_required
@ajax_required

def like(request):
    quote_id = request.POST['quote']
    quote    = Quote.objects.get(pk=quote_id)
    user     = request.user
    #like    = QuoteActivity.objects.filter(activity_type=QuoteActivity.LIKE, quote=quote_id, user=user)
    #like    = quote.likes.filter(activity_type=Activity.LIKE, user=user)
    try:
        like = Activity.objects.get(content_type=ContentType.objects.get_for_model(quote), object_id=quote.id, user=request.user)

        if like:
            """
            user.profile.unotify_liked(quote)
	    """
            like.delete()
            #Activity.objects.delete(content_object=quote, activity_type=Activity.LIKE, user=request.user)
        else:
            #like = QuoteActivity(activity_type=QuoteActivity.LIKE, quote=quote, user=user)
            #like.save()
            #quote.likes.create(activity_type=Activity.LIKE, user=user)
            like = Activity(activity_type=Activity.LIKE, content_object=quote, user=request.user)
            like.save()
            """
            user.profile.notify_liked(quote)
    	    """
    except Activity.DoesNotExist:
        quote.likes.create(activity_type=Activity.LIKE, user=user)
	
    #return HttpResponse(quote.calculate_likes())
    return HttpResponse(quote.likes.count())

desiquotes/quotes/templates/quotes/add_user_quote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes:home' %}">{% trans 'Quotes' %}</a></li>
    <li class="active">{% trans 'Write Quote' %}</li>
  </ol>
  <form action="{% url 'quotes:add_user_quote' %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <button type="button" class="btn btn-default preview" data-toggle="modal" data-target="#preview">{% trans 'Preview' %}</button>
      <a href="{% url 'quotes:home' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>

  <div class="modal fade" id="preview">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Quote Preview</h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock main %}

desiquotes/quotes/templates/quotes/drafts.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes:home' %}">{% trans 'Quotes' %}</a></li>
    <li class="active">{% trans 'Drafts' %}</li>
  </ol>
  {% comment "Optional note" %}
  {{ drafts|join:" || " }}
  {% endcomment %}

  <table class="table table-striped">
    <thead>
      <tr>
        <th>{% trans 'Content' %}</th>
        <th>{% trans 'Tags' %}</th>
      </tr>
    </thead>
    <tbody>
      {% for quote in drafts %}
        <tr>
          <td><a href="{% url 'quotes:edit_user_quote' quote.pk %}">{{ quote.content }}</a></td>
          <td>
	    {% comment "Optional method" %}
            {% for tag in quote.tags.names %}
	    {% endcomment %}
            {% for tag in quote.get_tags %}        
              <span class="label label-default">{{ tag }}</span>
            {% endfor %}
          </td>
        </tr>
      {% empty %}
        <tr>
          <td colspan="4" style="text-align: center">
            {% trans 'No draft to display' %}
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock main %}

desiquotes/quotes/templates/quotes/edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes' %}">{% trans 'Quotes' %}</a></li>
    <li><a href="{% url 'drafts' %}">{% trans 'Drafts' %}</a></li>
    <li class="active">{% trans 'Edit' %}</li>
  </ol>
  <form action="{% url 'edit_quote' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <a href="{% url 'drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock main %}

desiquotes/quotes/templates/quotes/edit_user_quote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes:home' %}">{% trans 'Quotes' %}</a></li>
    <li><a href="{% url 'quotes:drafts' %}">{% trans 'Drafts' %}</a></li>
    <li class="active">{% trans 'Edit' %}</li>
  </ol>
  <form action="{% url 'quotes:edit_user_quote' form.instance.pk %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <a href="{% url 'quotes:drafts' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>
{% endblock main %}

desiquotes/quotes/templates/quotes/partial_quote.html
{% load i18n %}
<quote>
  {% comment %}
  <h2><a href="{% url 'quotes' %}">{{ quote.content }}</a></h2>
  {% endcomment %}
  
  <div class="content">
    {{ quote.content }}
  </div>
  <div class="info">
  -- {{ quote.object_id.get_screen_name }}
  </div>
  <div class="info">
    <span class="date">
      <span class="glyphicon glyphicon-calendar"></span>
      {{ quote.create_date }}
    </span>
  </div>
  {% if quote.tags.names %}
    <div class="tags">
      {% for tag in quote.tags.names %}
        <a href="{% url 'quotes:tag' tag %}"><span class="label label-default">{{ tag }}</span></a>
      {% endfor %}
    </div>
  {% endif %}
   
  {% comment %} 
  {% for name, value in quote.get_fields %}
    {% if value %}
      {{ name }} => {{ value }}
    {% endif %}
  {% endfor %}
  {{ quote.create_user }}
  {{ user }}
  {% endcomment %}

  <div class="interaction info">
    {% if user in quotes.get_likers %}
      <a href="#" class="like unlike">
        <span class="glyphicon glyphicon-thumbs-up"></span>
        <span class="text">{% trans 'Unlike' %}</span>
        (<span class="like-count">{{ quote.get_likes }}</span>)
      </a>
    {% else %}
        <a href="#" class="like">
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <span class="text">{% trans 'Like' %}</span>
          (<span class="like-count">{{ quote.get_likes }}</span>)
        </a>
    {% endif %}

    {% if quote.object_id == user.id and quote.writer_type == quote.get_writer_type %}
      <span class="glyphicon glyphicon-trash remove-quote" title="{% trans 'Remove this quote' %}"></span>
      <span class="glyphicon glyphicon-pencil edit-quote" title="{% trans 'Edit this quote' %}"> </span>
    {% endif %}
  </div> 
</quote>

desiquotes/quotes/templates/quotes/quote.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}


{% block head %}
  <link href="{% static 'css/quotes.css' %}" rel="stylesheet">
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes:home' %}">{% trans 'Quotes' %}</a></li>
    <li class="active">{% trans 'Quote' %}</li>
  </ol>
  {% if quote.create_user == request.user %}
    <div>
      <a href="{% url 'quotes:edit_user_quote' quote.pk %}" class="btn btn-primary pull-right">
        <span class="glyphicon glyphicon-pencil"></span> {% trans "Edit Quote" %}
      </a>
    </div>
  {% endif %}
  {% include 'quotes/partial_quote.html' with quote=quote %}
{% endblock main %}

desiquotes/quotes/templates/quotes/quotes.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %} {% trans 'Quotes' %} {% endblock %}

{% block head %}
  <link href="{% static 'css/quotes.css' %}" rel="stylesheet">
  <link href="{% static 'css/masonry.css' %}" rel="stylesheet">
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
        
    {% if user.is_authenticated %}
    <a href="{% url 'quotes:add_user_quote' %}" class="btn btn-primary pull-right">
      <span class="glyphicon glyphicon-pencil"></span> {% trans 'Write Quote' %}
    </a>
    <a href="{% url 'quotes:drafts' %}" class="btn btn-default pull-right" style="margin-right: .8em">{% trans 'Drafts' %}</a>
    {% endif %}
    <h1>{% trans 'Quote' %}</h1>
  </div>

  {% if quotes %}
  <div class="masonry">
        {% for quote in quotes %}
	  <div class="item" quote-id="{{ quote.pk }}" csrf="{{ csrf_token }}">
          {% include 'quotes/partial_quote.html' with quote=quote %}
	  </div>
        {% endfor %}
  </div>
  {% else %}
        <h4 class="no-data">{% trans 'There is no published quote yet' %}. <a href="{% url 'quotes:add_user_quote' %}">{% trans 'Be the first one to publish' %}!</a></h4>

  {% endif %}

  <div class="row">
    <div class="col-md-12">
      {% include 'paginator.html' with paginator=quotes %}
    </div>
  </div>


{% endblock main %}

desiquotes/quotes/templates/quotes/write.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <script src="{% static 'js/quotes.js' %}"></script>
{% endblock head %}

{% block main %}
  <ol class="breadcrumb">
    <li><a href="{% url 'quotes' %}">{% trans 'Quotes' %}</a></li>
    <li class="active">{% trans 'Write Quote' %}</li>
  </ol>
  <form action="{% url 'write' %}" method="post" role="form">
    {% csrf_token %}
    {{ form.status }}
    {% for field in form.visible_fields %}
      <div class="form-group{% if field.errors %} has-error{% endif %}">
        <label for="{{ field.label }}" class="control-label">{{ field.label }}</label>
        {{ field }}
        {% if field.help_text %}
          <span class="help-block">{{ field.help_text }}</span>
        {% endif %}
        {% for error in field.errors %}
          <label class="control-label">{{ error }}</label>
        {% endfor %}
      </div>
    {% endfor %}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish">{% trans 'Publish' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Save Draft' %}</button>
      <button type="button" class="btn btn-default preview" data-toggle="modal" data-target="#preview">{% trans 'Preview' %}</button>
      <a href="{% url 'quotes' %}" class="btn btn-default">{% trans 'Cancel' %}</a>
    </div>
  </form>

  <div class="modal fade" id="preview">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Quote Preview</h4>
        </div>
        <div class="modal-body"></div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

{% endblock main %}